### ISSUE TITLE
Busca não funciona (erro: Selecione pelo menos 1 data de saída)

### ISSUE THREAD

**Issue by DanCaparroz** [brenovieira/extension#12]
Independente do filtro que faço recebo a mesma mensagem: Selecione pelo menos 1 data de saída

![image](https://cloud.githubusercontent.com/assets/12939511/10763175/0d21101c-7cb0-11e5-80e7-b342cff2441b.png)

Outro filtro:

![image](https://cloud.githubusercontent.com/assets/12939511/10763208/2ded7420-7cb0-11e5-95f5-389cb9b6813f.png)

**Comment by brenovieira** [comment]
[$timeout don't play together with bootstrap datepicker](https://github.com/brenovieira/extension/commit/be47bf243dade232f86487b84eb7100bc811b06c) fix this.
I'm releasing v2.4.1.
