### ISSUE TITLE
Erro após atualização / Error after update

### ISSUE THREAD

**Issue by andreluigo** [brenovieira/extension#3]
Após a atualização não está mais funcionando. // It is not working after updating.

**Comment by brenovieira** [comment]
@andreluigo,
Can you send me the error ? or some print screen ?

It's probably some error on angular that not renders correctly.
Maybe some TypeError (when you try to access property of undefined, for example).

Just open the extension (click on the airplane icon), open devTools (Ctrl + Shift + i), and copy what appears on console.

**Comment by andreluigo** [comment]
Refused to load plugin data from '' because it violates the following Content Security Policy directive: "object-src assets-cdn.github.com".

WebSocket connection to 'wss://live.github.com/_sockets/MTA0NzY5MTM6YjhlOGNhMzAyOTgwOWVmMDA5MjEwMmEz…NGE0ZjYzMTI2ODE2NmJiODZmMDhjNQ==--e25dbf885f78baf9f506a30cfd58f23f53401f99' failed: WebSocket is closed before the connection is established.

**Comment by brenovieira** [comment]
Actually, I think maybe you open devTools from another window.

Because the extension doesn't include anything from github.
> object-src assets-cdn.github.com

Can you please try to open the extension, right click on the popup, and click "Inspecionar elemento" or "Inspect element" ?

that way you will open the devTools from the extension window.
And copy here what's on console

**Comment by andreluigo** [comment]
Acho que vc é brasileiro...
Realmente estava pegando a depuração da página e não da extensão.
Depurando a extensão, a aba console fica em branco.
---------------------------
I think you are brazilian...
Actually I was deploying github webpage instead the extension.
Deploying the extension, the console tab stays blank.

**Comment by brenovieira** [comment]
hahaha
yes, I'm brazilian, but some other guys (not brazilian) will start to work on the extension as well.
Few days from now, we'll actually have this extension deployed on more countries.

So I prefer to speak in English here to everyone understand it.
Other chance to practice english ! ; )

So, the console is blank..
Are you choosing the site ?

Because I noticed now there isn't a default value neither a validation, but it is a necessary field.

![issue3](https://cloud.githubusercontent.com/assets/7158650/10203065/62785d3a-678a-11e5-84c6-dd95f5387e8d.png)

Can you also try to click on trash icon, because it delete past searches.
The last version the data format was different.
So it can cause some problem.

**Comment by brenovieira** [comment]
Note: I'm gonna add a default value to site field.

**Comment by andreluigo** [comment]
Even after delete history i was getting errors and searching was not running.
But after some trials seems to be working!

**Comment by brenovieira** [comment]
Oh great !!!

I still have to discover what the problem was.
Other person told me it wasn't working too and I don't know why, since I tested in two computers (a windows and a macook) and it is working fine.

**Comment by andreluigo** [comment]
The new version is great and quite more beautiful, but a little thing that got worse, in my opinion, is that now we can't select dates in a time interval of two months or more on unique search. Could you put this back!

**Comment by brenovieira** [comment]
Why ?

I think you can select as many dates as you want.
I took off "select whole month" button, but I added a "select range" option.

So now you can select two entire months just clicking on the first day and the last day of second month. Somethink like that:

![issue3-2](https://cloud.githubusercontent.com/assets/7158650/10204628/42e4e782-6793-11e5-9dc1-2665e39f6cd8.png)

I selected 1 october and 30 november.
Or you can pick manually all dates you want, leaving the "select range" dismarked:

![issue3-3](https://cloud.githubusercontent.com/assets/7158650/10204695/9f56d6a6-6793-11e5-9efd-1f6bcae83c20.png)

Does it solve your needs ?

**Comment by andreluigo** [comment]
Here doesn't work. Selecting dates on october and changing for november loses selection dates on october.

**Comment by brenovieira** [comment]
Really ? I don't know why too.

You need to select the departure dates first ant then select return dates.
But I don't see why changing the month would reset selected dates.

**Comment by brenovieira** [comment]
Hi @andreluigo,
I maybe discovered your problem.

The PR #5 may solve your issue.
I'll deploy a new version v2.2.
Please, see if it is enough.

**Comment by andreluigo** [comment]
Ok...
Thank you and sorry for being annoying!

**Comment by brenovieira** [comment]
:+1: 

Does it correct the problem ?
Is the extension working now ?

**Comment by andreluigo** [comment]
Actually i think it didn't update... But it seems to be working. Only selection in multiple months still doesn't.

**Comment by brenovieira** [comment]
Could you enter here: chrome://extensions/?id=eibkppkjgpngoddnomoladcocbenooij
and see if the version is 2.2 ?

Theoretically, it update few minutes after I publish what I did 12 hours ago.
So it should be updated.

**Comment by andreluigo** [comment]
Yes, updated!

**Comment by brenovieira** [comment]
Great.

> Only selection in multiple months still doesn't.
I'll leave this issue open until somebody finds what is this datepicker issue.

I didn't change that part as I don't know what is happening and it's working in all computers I tested.
Thanks

**Comment by Dfralmeida** [comment]
Breno,
Inicialmente parabéns pelo plugin, é simples de usar e muito util. Gostei da renovada na interface, melhor que a anterior,  mas estranhamente depois desta atualização a busca não retorna nada, fica "Carregando 2 datas ..." só. Fiz teste para Smiles, Decolar, TAM, sempre assim. Testei em duas maquinas. Seria por você estar ajustando? Uma vez consegui fazer com que retornasse, mas voltou como [Object] -[Object] para origem-destino.
![erro passagens](https://cloud.githubusercontent.com/assets/14954023/10263307/c84c1dae-69bf-11e5-92bc-00b943347634.png)

Um grande abraço!

**Comment by Dfralmeida** [comment]
Outra ideia que eu queria dar. Será que é possível implementar um botão para que a simulação seja efetuada de tempos em tempos? Seria legal para enviar e-mail caso o valor da passagem mudasse :)

**Comment by brenovieira** [comment]
Fala @Dfralmeida ,

Você pode apertar no icone da lixeira ?
Parece que os dados que a busca que estava salva está em um formato diferente.
Teoricamente, tem um codigo que limpa a busca antiga se ela estiver no formato antigo, mas parece que não funcionou no seu computador.

![captura de tela 2015-10-03 as 11 19 41](https://cloud.githubusercontent.com/assets/7158650/10263334/1d7211e8-69c1-11e5-8bb3-5a988b0acfdb.png)

Tá vendo como aparece o rio de janeiro ?

> Outra ideia que eu queria dar. Será que é possível implementar um botão para que a simulação seja efetuada de tempos em tempos? Seria legal para enviar e-mail caso o valor da passagem mudasse :)

Essa opção "Avisar quando o preço baixar" faz exatamente isso.
________________________
In english to everyone understand it:

Hi @Dfralmeida ,

Can you click on trash icon ?
It seems your saved search is in a different format.
Theoretically, there is a code to delete this search in a different format, but it seems to be working incorrectly in your computer.

![captura de tela 2015-10-03 as 11 19 41](https://cloud.githubusercontent.com/assets/7158650/10263334/1d7211e8-69c1-11e5-8bb3-5a988b0acfdb.png)

Are you seeing how "rio de janeiro" appears ?

> Outra ideia que eu queria dar. Será que é possível implementar um botão para que a simulação seja efetuada de tempos em tempos? Seria legal para enviar e-mail caso o valor da passagem mudasse :)

The option "Tell me about lower fares" does exactly that.

**Comment by Dfralmeida** [comment]
Excelent! The problem was really due to old code. After pressing the trash icon the plugin worked fine, just as expected. Regarding the "Tell me about lower fares". That's really good to know. 
Thank you for what you've been doing, the plugin is one of the best things I've seen on chrome. 

Valeeeeeeeeu!

**Comment by brenovieira** [comment]
hahhaa. thank you!
