### ISSUE TITLE
Wrong Airport IATA

### ISSUE THREAD

**Issue by psbaj** [brenovieira/extension#4]
Hello,
The IATA for Sydney airport is wrong. The correct is SYD, if you type Sydney in the app it shows SDY and do not find results, because this airport do not exist.

**Comment by brenovieira** [comment]
Hi @psbaj ,

Actually there is a SDY also.
It refers to an airport on the United States: [Sidney–Richland Municipal Airport](https://en.wikipedia.org/wiki/Sidney%E2%80%93Richland_Municipal_Airport)

But I'll solve this problem putting the most popular touristic cities before others.
I'm gonna use these lists as parameter:

https://en.wikipedia.org/wiki/World_Tourism_rankings
http://www.tripadvisor.com/TravelersChoice-Destinations
